SEARCH_SUPPLEMENT_GROUPS = {
    "meieri_og_frokost": [
        "egg",
        "10pk egg",
        "12pk egg",
        "bakketun egg",
        "frittgaende egg",
        "prior egg",
        "frokostegg",
        "melk",
        "tinemelk",
        "lettmelk",
        "helmelk",
        "skummetmelk",
        "q melk",
        "smør",
        "meierismør",
        "lettsmør",
        "lurpak",
        "brelett",
        "bremykt",
        "soyasmør",
        "ost",
        "norvegia",
        "jarlsberg",
        "gulost",
        "hvitost",
        "cheddar",
        "mozzarella",
        "yoghurt",
        "skyr",
        "kesam",
        "rømme",
        "fløte",
        "creme fraiche",
        "cottage cheese",
        "kefir",
        "havregryn",
        "müsli",
        "frokostblanding",
        "granola",
        "cornflakes",
    ],
    "bakst_og_palegg": [
        "brød",
        "grovbrød",
        "kneippbrød",
        "speltbrød",
        "speltbrod",
        "toastbrød",
        "burgerbrød",
        "rundstykker",
        "knekkebrød",
        "bagett",
        "baguette",
        "wrap",
        "tortilla",
        "pitabrød",
        "croissant",
        "bolle",
        "boller",
        "kake",
        "sjokoladekake",
        "sjokoladekake langpanne",
        "langpannekake",
        "kjeks",
        "pålegg",
        "skinke",
        "salami",
        "servelat",
        "leverpostei",
        "makrell i tomat",
        "syltetøy",
        "hummus",
        "smøreost",
        "prim",
    ],
    "frukt_gront_salater": [
        "frukt",
        "frukt og grønt",
        "grønnsaker",
        "gront",
        "ferske grønnsaker",
        "fersk frukt",
        "avocado",
        "banan",
        "eple",
        "appelsin",
        "pære",
        "druer",
        "jordbær",
        "blåbær",
        "bringebær",
        "sitron",
        "lime",
        "avokado",
        "kiwi",
        "melon",
        "vannmelon",
        "mango",
        "ananas",
        "clementin",
        "mandarin",
        "plommer",
        "fersken",
        "nektarin",
        "tomat",
        "cherrytomat",
        "agurk",
        "potet",
        "gulrot",
        "løk",
        "brokkoli",
        "blomkål",
        "kål",
        "spinat",
        "sopp",
        "champignon",
        "purre",
        "hvitløk",
        "ingefær",
        "chili",
        "mais",
        "selleri",
        "asparges",
        "sukkererter",
        "erter",
        "paprika",
        "salat",
        "hjertesalat",
        "crispy salat",
        "roman salat",
        "isbergsalat",
        "ruccola",
        "babyleaf",
        "salatmix",
        "salatblanding",
    ],
    "middag_og_protein": [
        "kjøttdeig",
        "deig",
        "kylling",
        "kyllingfilet",
        "kyllinglår",
        "kotelett",
        "koteletter",
        "svinekotelett",
        "nakkekotelett",
        "ribbe",
        "grillribbe",
        "svineribbe",
        "pølse",
        "pølser",
        "wienerpølser",
        "grillpølser",
        "bacon",
        "karbonadedeig",
        "hamburger",
        "pizza",
        "pai",
        "middag",
        "ferdigmat",
        "laks",
        "torsk",
        "fisk",
        "lofoten",
        "lofotburger",
        "fiskeburger",
        "fiskeburger lofoten",
        "fiskekaker",
        "fiskeboller",
        "reker",
        "scampi",
    ],
    "torrvarer_og_sauser": [
        "pasta",
        "tagliatelle",
        "fersk tagliatelle",
        "spagetti",
        "spaghetti",
        "nudler",
        "lasagne",
        "middagssaus",
        "pastasaus",
        "pesto",
        "suppe",
        "buljong",
        "ris",
        "ketchup",
        "tomatketchup",
        "sennep",
        "majones",
        "pannekaker",
        "pannekakemix",
        "pannekake mix",
        "taco",
        "tacolefse",
        "tortillachips",
        "salsa",
        "tacosaus",
        "bønner",
        "linser",
        "hermetikk",
        "sukker",
        "salt",
        "mel",
        "hvetemel",
        "bakemiks",
        "gjær",
        "vaniljesukker",
        "bakepulver",
        "eddik",
        "olje",
        "olivenolje",
        "smakstilsetning",
        "krydder",
        "pepper",
    ],
    "drikke_frossen_og_snacks": [
        "havremelk",
        "mandelmelk",
        "brus",
        "coca-cola",
        "coca cola",
        "coca cola zero",
        "cola zero",
        "coca cola zero 1,5lx8",
        "coca cola zero 1.5lx8",
        "coca cola 1,5lx8",
        "coca cola 1.5lx8",
        "1,5lx8",
        "1.5lx8",
        "mineralvann",
        "energidrikk",
        "iste",
        "saft",
        "vann",
        "juice",
        "appelsinjuice",
        "eplejuice",
        "kaffe",
        "filterkaffe",
        "te",
        "kakao",
        "sjokolade",
        "sjokoladekake",
        "godteri",
        "potetgull",
        "snacks",
        "nøtter",
        "frossenpizza",
        "frossen",
        "frosne bær",
        "grønnsaksblanding",
        "iskrem",
        "is",
    ],
    "hygiene_baby_dyr": [
        "tannkrem",
        "tannbørste",
        "munnskyll",
        "bind",
        "tamponger",
        "barberhøvel",
        "barberskum",
        "toalettpapir",
        "dopapir",
        "torkepapir",
        "kjokkenpapir",
        "papir",
        "sjampo",
        "balsam",
        "dusjsape",
        "handsape",
        "deodorant",
        "solkrem",
        "shower gel",
        "vaskemiddel",
        "oppvaskmiddel",
        "blekemiddel",
        "renhold",
        "såpe",
        "vaskeservietter",
        "baby",
        "barnemat",
        "bleier",
        "våtservietter",
        "morsmelkerstatning",
        "grøt",
        "hundemat",
        "kattemat",
        "dyremat",
        "kattesand",
        "sminke",
        "makeup",
        "kosmetikk",
        "leppepomade",
        "leppestift",
        "mascara",
        "foundation",
        "concealer",
        "pudder",
        "rouge",
        "eyeliner",
        "neglelakk",
        "sminkefjerner",
        "ansiktskrem",
        "hudpleie",
    ],
    "kiosk_og_lesestoff": [
        "donald",
        "pocket",
        "ukeblad",
        "magasin",
        "kryssord",
        "se og hør",
        "aftenposten",
        "dagbladet",
        "klassekampen",
        "finansavisen",
        "avis",
    ],
}


def flattened_search_supplements():
    items = []
    seen = set()
    for group_items in SEARCH_SUPPLEMENT_GROUPS.values():
        for item in group_items:
            key = item.strip().lower()
            if not key or key in seen:
                continue
            seen.add(key)
            items.append(item)
    return items
